---
- hosts: all
  name: Install repository
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  pre_tasks:
    - name: Initialize the user defined variables
      set_fact:
        enable_edb_repo: false

  roles:
    - role: setup_repo

- hosts: dbt2_driver
  name: Install DBT2 driver
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  roles:
    - role: setup_dbt2_driver

- hosts: dbt2_client
  name: Install DBT2 client
  become: true
  gather_facts: true

  collections:
    - edb_devops.edb_postgres

  roles:
    - role: setup_dbt2_client
    - role: install_dbserver

  tasks:
    - name: Update /var/lib/pgsql/.pgpass
      ansible.builtin.lineinfile:
        path: /var/lib/pgsql/.pgpass
        regexp: ^\*:\*:\*:postgres.*
        line: "*:*:*:postgres:{{ pg_password }}"
        owner: "{{ pg_owner }}"
        group: "{{ pg_group }}"
        mode: "0600"
      become: true
